# Generated by Django 5.0.2 on 2024-03-06 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_remove_productcategory_category_img'),
        ('SellerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AudioModel',
            new_name='AudioSpecificationModel',
        ),
        migrations.RenameModel(
            old_name='ProductDiscount',
            new_name='ProductDiscountModel',
        ),
        migrations.RenameModel(
            old_name='SmartPhoneModel',
            new_name='SmartPhoneSpecificationModel',
        ),
        migrations.RenameModel(
            old_name='TeleVisionModels',
            new_name='TeleVisionSpecificationModels',
        ),
        migrations.AlterModelTable(
            name='audiospecificationmodel',
            table='audio_spec_model',
        ),
        migrations.AlterModelTable(
            name='pcspecificationmodel',
            table='pc_spec_model',
        ),
        migrations.AlterModelTable(
            name='smartphonespecificationmodel',
            table='smartphone_spec_model',
        ),
        migrations.AlterModelTable(
            name='televisionspecificationmodels',
            table='Television_spec_model',
        ),
    ]
