# Generated by Django 5.0.2 on 2024-03-09 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_brandmodel'),
        ('SellerApp', '0002_rename_audiomodel_audiospecificationmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiospecificationmodel',
            name='product_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.brandmodel'),
        ),
        migrations.AddField(
            model_name='pcspecificationmodel',
            name='product_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.brandmodel'),
        ),
        migrations.AddField(
            model_name='smartphonespecificationmodel',
            name='product_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.brandmodel'),
        ),
        migrations.AddField(
            model_name='televisionspecificationmodels',
            name='product_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.brandmodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.brandmodel'),
        ),
    ]
