# Generated by Django 5.0.2 on 2024-03-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0003_audiospecificationmodel_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_stock',
            field=models.IntegerField(null=True),
        ),
    ]
