# Generated by Django 5.0.2 on 2024-03-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0004_productmodel_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='seller_product_quantity',
            new_name='seller_product_stock',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='product_stock',
        ),
    ]
