# Generated by Django 5.0.2 on 2024-03-11 07:42

import SellerApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0005_rename_seller_product_quantity_productmodel_seller_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiospecificationmodel',
            name='product_brand',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pcspecificationmodel',
            name='product_brand',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='product_image',
            field=models.ImageField(upload_to=SellerApp.models.upload_to_path),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_brand',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='smartphonespecificationmodel',
            name='product_brand',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='televisionspecificationmodels',
            name='product_brand',
            field=models.CharField(max_length=15),
        ),
    ]
