# Generated by Django 5.0.2 on 2024-03-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0006_alter_audiospecificationmodel_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_description',
            field=models.CharField(max_length=500),
        ),
    ]
