# Generated by Django 5.0.2 on 2024-03-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0007_alter_productmodel_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcspecificationmodel',
            name='spec_processor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='smartphonespecificationmodel',
            name='spec_processor',
            field=models.CharField(max_length=50),
        ),
    ]
