# Generated by Django 5.0.2 on 2024-03-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0008_alter_pcspecificationmodel_spec_processor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcspecificationmodel',
            old_name='spec_resolution',
            new_name='spec_horizontal_resolution',
        ),
        migrations.RenameField(
            model_name='smartphonespecificationmodel',
            old_name='spec_resolution',
            new_name='spec_horizontal_resolution',
        ),
        migrations.RenameField(
            model_name='televisionspecificationmodels',
            old_name='spec_resolution',
            new_name='spec_horizontal_resolution',
        ),
        migrations.AddField(
            model_name='pcspecificationmodel',
            name='spec_vertical_resolution',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='smartphonespecificationmodel',
            name='spec_vertical_resolution',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='televisionspecificationmodels',
            name='spec_vertical_resolution',
            field=models.IntegerField(null=True),
        ),
    ]
