# Generated by Django 5.0.2 on 2024-03-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0009_rename_spec_resolution_pcspecificationmodel_spec_horizontal_resolution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiospecificationmodel',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='pcspecificationmodel',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='smartphonespecificationmodel',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='televisionspecificationmodels',
            name='product_price',
        ),
    ]
