# Generated by Django 5.0.2 on 2024-03-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0010_remove_audiospecificationmodel_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcspecificationmodel',
            name='spec_display_size',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='smartphonespecificationmodel',
            name='spec_display_size',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='televisionspecificationmodels',
            name='spec_display_size',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
