# Generated by Django 5.0.2 on 2024-03-11 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0011_alter_pcspecificationmodel_spec_display_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='user_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
