# Generated by Django 5.0.2 on 2024-03-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0012_productmodel_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcspecificationmodel',
            name='spec_gpu',
            field=models.CharField(max_length=50),
        ),
    ]
