# Generated by Django 5.0.2 on 2024-03-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0013_alter_pcspecificationmodel_spec_gpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiospecificationmodel',
            name='spec_latency',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
