# Generated by Django 5.0.2 on 2024-03-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0014_alter_audiospecificationmodel_spec_latency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiospecificationmodel',
            name='spec_latency',
            field=models.IntegerField(),
        ),
    ]
