# Generated by Django 5.0.2 on 2024-03-12 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0016_alter_productimagemodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='user_rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
