# Generated by Django 5.0.2 on 2024-03-12 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0017_alter_productmodel_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='user_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
