# Generated by Django 5.0.2 on 2024-03-13 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0018_alter_productmodel_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphonespecificationmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='SellerApp.productmodel'),
        ),
    ]
