# Generated by Django 5.0.2 on 2024-03-16 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0019_alter_smartphonespecificationmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiospecificationmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Audio', to='SellerApp.productmodel'),
        ),
        migrations.AlterField(
            model_name='pcspecificationmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Computer', to='SellerApp.productmodel'),
        ),
    ]
