# Generated by Django 5.0.2 on 2024-03-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0020_alter_audiospecificationmodel_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiospecificationmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='SellerApp.productmodel'),
        ),
        migrations.AlterField(
            model_name='pcspecificationmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer', to='SellerApp.productmodel'),
        ),
    ]
