# Generated by Django 5.0.2 on 2024-03-25 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0021_alter_audiospecificationmodel_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscountmodel',
            name='seller_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SellerApp.sellerdatamodel'),
        ),
    ]
