# Generated by Django 5.0.2 on 2024-04-02 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0022_productdiscountmodel_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisionspecificationmodels',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='television', to='SellerApp.productmodel'),
        ),
    ]
