# Generated by Django 5.0.2 on 2024-04-12 15:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0023_alter_televisionspecificationmodels_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscountmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdiscountmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdiscounts', to='SellerApp.productmodel'),
        ),
    ]
