# Generated by Django 5.0.2 on 2024-04-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0024_productdiscountmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiospecificationmodel',
            name='product_status',
            field=models.CharField(default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='pcspecificationmodel',
            name='product_status',
            field=models.CharField(default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_status',
            field=models.CharField(default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='sellerdatamodel',
            name='seller_status',
            field=models.CharField(default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='smartphonespecificationmodel',
            name='product_status',
            field=models.CharField(default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='televisionspecificationmodels',
            name='product_status',
            field=models.CharField(default='active', max_length=8),
        ),
    ]
