# Generated by Django 5.0.2 on 2024-04-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0025_alter_audiospecificationmodel_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcspecificationmodel',
            name='spec_gpu',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
