# Generated by Django 5.0.2 on 2024-04-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0027_remove_pcspecificationmodel_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiospecificationmodel',
            name='product_img',
        ),
        migrations.RemoveField(
            model_name='smartphonespecificationmodel',
            name='product_img',
        ),
        migrations.RemoveField(
            model_name='televisionspecificationmodels',
            name='product_img',
        ),
    ]
