# Generated by Django 5.0.2 on 2024-04-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0028_remove_audiospecificationmodel_product_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_name',
            field=models.CharField(max_length=500),
        ),
    ]
