# Generated by Django 5.0.2 on 2024-04-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0029_alter_productmodel_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiospecificationmodel',
            name='spec_bluetooth',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
