# Generated by Django 5.0.2 on 2024-04-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0030_alter_audiospecificationmodel_spec_bluetooth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiospecificationmodel',
            name='spec_playback',
            field=models.IntegerField(),
        ),
    ]
