# Generated by Django 5.0.2 on 2024-04-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0031_alter_audiospecificationmodel_spec_playback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdatamodel',
            name='seller_email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerdatamodel',
            name='seller_gst',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerdatamodel',
            name='seller_licence',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerdatamodel',
            name='seller_pan',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerdatamodel',
            name='seller_phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
