# Generated by Django 5.0.2 on 2024-05-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0032_alter_sellerdatamodel_seller_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='seller_product_stock',
            new_name='product_stock',
        ),
    ]
