# Generated by Django 5.0.2 on 2024-03-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDataModel',
            fields=[
                ('adm_ID', models.AutoField(primary_key=True, serialize=False)),
                ('adm_username', models.CharField(max_length=20)),
                ('adm_password', models.CharField(max_length=20)),
                ('adm_email', models.CharField(max_length=50)),
                ('adm_phone', models.CharField(max_length=15)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_data_model',
            },
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_img', models.ImageField(upload_to='', verbose_name='events/')),
                ('discount_start_date', models.DateTimeField(auto_now_add=True)),
                ('discount_end_date', models.DateTimeField()),
                ('status', models.CharField(default='Active', max_length=100)),
            ],
            options={
                'db_table': 'event_model',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('category_img', models.ImageField(upload_to='', verbose_name='category/')),
            ],
            options={
                'db_table': 'product_category_model',
            },
        ),
    ]
