# Generated by Django 5.0.2 on 2024-03-06 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category_img',
        ),
    ]
