# Generated by Django 5.0.2 on 2024-03-06 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_remove_productcategory_category_img'),
        ('SellerApp', '0002_rename_audiomodel_audiospecificationmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductCategoryModel',
        ),
    ]
