# Generated by Django 5.0.2 on 2024-03-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_productbrandmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='category_image',
            field=models.ImageField(null=True, upload_to='categories'),
        ),
    ]
