# Generated by Django 5.0.2 on 2024-03-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_productcategorymodel_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='event_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.productcategorymodel'),
        ),
    ]
