# Generated by Django 5.0.2 on 2024-04-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_alter_eventmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindatamodel',
            name='adm_email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='admindatamodel',
            name='adm_phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='admindatamodel',
            name='adm_username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
