# Generated by Django 5.0.2 on 2024-05-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_alter_admindatamodel_adm_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodel',
            name='category_image',
            field=models.ImageField(null=True, upload_to='categories/'),
        ),
    ]
