# Generated by Django 5.0.2 on 2024-03-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatamodel',
            name='user_profile_img',
            field=models.ImageField(upload_to='profile_pic/'),
        ),
    ]
