# Generated by Django 5.0.2 on 2024-03-10 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_userdatamodel_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdatamodel',
            name='user_rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
