# Generated by Django 5.0.2 on 2024-03-11 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_alter_reviewdatamodel_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdatamodel',
            name='user_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
