# Generated by Django 5.0.2 on 2024-04-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_reviewdatamodel_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatamodel',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdatamodel',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
