# Generated by Django 5.0.2 on 2024-04-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_userdatamodel_first_name_userdatamodel_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdatamodel',
            name='cart_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
