# Generated by Django 5.0.2 on 2024-04-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_cartdatamodel_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressdatamodel',
            name='phone_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
