# Generated by Django 5.0.2 on 2024-04-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_useraddressdatamodel_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdatamodel',
            name='user_review',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
