# Generated by Django 5.0.2 on 2024-04-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_alter_reviewdatamodel_user_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdatamodel',
            name='review_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
