# Generated by Django 5.0.2 on 2024-04-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_reviewdatamodel_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatamodel',
            name='user_profile_img',
            field=models.ImageField(null=True, upload_to='profile_pic/'),
        ),
    ]
