# Generated by Django 5.0.2 on 2024-04-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_alter_userdatamodel_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatamodel',
            name='user_email',
            field=models.EmailField(max_length=100),
        ),
    ]
