# Generated by Django 5.0.2 on 2024-04-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_alter_userdatamodel_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdatamodel',
            old_name='first_name',
            new_name='user_first_name',
        ),
        migrations.RenameField(
            model_name='userdatamodel',
            old_name='last_name',
            new_name='user_last_name',
        ),
    ]
