# Generated by Django 5.0.2 on 2024-04-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_rename_first_name_userdatamodel_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatamodel',
            name='user_status',
            field=models.CharField(default='active', max_length=8),
        ),
    ]
