# Generated by Django 5.0.2 on 2024-04-27 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_alter_userdatamodel_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailsmodel',
            name='billing_ref_no',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='orderdetailsmodel',
            name='status',
            field=models.TextField(default='', max_length=10),
        ),
    ]
