# Generated by Django 5.0.2 on 2024-04-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_alter_orderdetailsmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailsmodel',
            name='order_cost',
            field=models.IntegerField(null=True),
        ),
    ]
