# Generated by Django 5.0.2 on 2024-04-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0018_orderdetailsmodel_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailsmodel',
            name='status',
            field=models.TextField(default='dispatched', max_length=10),
        ),
    ]
