# Generated by Django 5.0.2 on 2024-04-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0020_orderdetailsmodel_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailsmodel',
            name='billing_ref_no',
            field=models.IntegerField(unique=True),
        ),
    ]
