# Generated by Django 5.0.2 on 2024-05-07 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0022_reviewdatamodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewdatamodel',
            name='status',
        ),
    ]
